### PR TITLE
Pedro/svg sprites

### PR DESCRIPTION
**Pull request by pmpinto**
Hey @stkao05!
Very quick fix for multi SVG sprite configs.

### CODE REVIEW

**Comment by stvnkao** [comment]
Hi @pmpinto 
I think you accidentally include the `.DS_Store` file.

**Comment by pmpinto** [comment]
Oops...
Just noticed my `.gitignore` file was not including it. Should we even sync `.gitignore`?

Feel free to ignore the `.DS_Store`.

**Comment by stvnkao** [comment]
Please remove the file `.DS_Store` @pmpinto. We should not commit unused files and tell the collaborators to "just ignroe them".

**Comment by pmpinto** [comment]
Shame on me @stkao05 🙈

**Pull request closed without merging**
